// Runs the checker over the labeled set and writes evidence/labeled-report.md with caught/missed per problem type.
import assert from 'node:assert/strict';
import { writeFileSync, mkdirSync } from 'node:fs';
import test from 'node:test';
import { check } from '../engine.js';
import { CONTROLS, REPORTED, DOCUMENTED } from './labeled-set.js';

const run = c => check(c.workflow(), c.listing || '', { version: c.version });
const results = [];

for (const c of CONTROLS) {
  test(`control has no false alarm: ${c.name}`, () => {
    const r = run(c);
    assert.ok(r.ok, r.message);
    const alarms = r.findings.filter(f => ['fail', 'warn', 'dormant'].includes(f.status));
    assert.deepEqual(alarms.map(f => `${f.id}: ${f.title}`), []);
    assert.ok(r.passes.length >= 2);
    results.push({ kind: 'control', name: c.name, format: r.format, alarms: alarms.length, info: r.findings.filter(f => f.status === 'info').map(f => f.id), passes: r.passes.length });
  });
}

for (const c of REPORTED) {
  test(`reported ${c.id} ${c.config}`, () => {
    const r = run(c);
    assert.ok(r.ok, r.message);
    const hit = c.expect ? r.findings.find(f => f.id === c.expect) : null;
    if (c.expect) assert.ok(hit, `${c.id} expected ${c.expect}; got ${r.findings.map(f => f.id).join(', ')}`);
    else assert.equal(r.findings.filter(f => ['fail', 'warn'].includes(f.status)).length, 0, `${c.id} is a clean workflow`);
    results.push({ kind: 'reported', ...c, caught: !!hit, status: hit?.status, title: hit?.title });
  });
}

for (const c of DOCUMENTED) {
  test(`documented ${c.id} ${c.config}`, () => {
    const r = run(c);
    const hit = r.findings.find(f => f.id === c.expect);
    assert.ok(hit, `${c.id} expected ${c.expect}; got ${r.findings.map(f => f.id).join(', ')}`);
    assert.equal(hit.status, c.status);
    results.push({ kind: 'documented', ...c, caught: true, title: hit.title });
  });
}

const esc = s => String(s).replace(/\|/g, '\\|');
test.after(() => {
  const rep = results.filter(r => r.kind === 'reported');
  const types = ['files', 'nodes', 'pe', 'vram', 'outside'];
  const per = types.map(t => { const xs = rep.filter(r => r.type === t); return [t, xs.filter(r => r.caught).length, xs.length]; });
  const caught = rep.filter(r => r.caught).length;
  const lines = [
    '# Labeled set: caught and missed', '',
    `Generated by \`npm test\` on ${new Date().toISOString().slice(0, 10)}. Every reported case is an edit of an official Comfy-Org template (fixtures/official).`, '',
    `**Reported problems caught: ${caught} of ${rep.length} (${Math.round(100 * caught / rep.length)}%).** Stop rule: stop below 50%.`, '',
    '| Problem type | Caught | Of |', '|---|---|---|', ...per.map(([t, a, b]) => `| ${t} | ${a} | ${b} |`), '',
    '## Controls (must raise no fail, warning or dormant finding)', '',
    '| Control | Format | Alarms | Info notes | Passes |', '|---|---|---|---|---|',
    ...results.filter(r => r.kind === 'control').map(r => `| ${r.name} | ${r.format} | ${r.alarms} | ${r.info.join(', ') || '–'} | ${r.passes} |`), '',
    '## Reported cases', '',
    '| ID | Type | Thread | Rebuilt configuration | Expected rule | Result | ComfyUI today |', '|---|---|---|---|---|---|---|',
    ...rep.map(r => `| ${r.id} | ${r.type} | ${r.thread} | ${r.config}${r.assumption ? ` (${r.assumption})` : ''}${r.version ? `; version ${r.version}` : ''} | ${r.expect || '–'} | ${r.caught ? `caught (${r.status})` : 'missed'} | ${r.flaggedToday} |`), '',
    '## Documented rules (source code or Qwen docs; not counted above)', '',
    '| ID | Configuration | Rule | Status |', '|---|---|---|---|',
    ...results.filter(r => r.kind === 'documented').map(r => `| ${r.id} | ${esc(r.config)} | ${r.expect} | ${r.status} |`), '',
  ];
  mkdirSync(new URL('../evidence/', import.meta.url), { recursive: true });
  writeFileSync(new URL('../evidence/labeled-report.md', import.meta.url), lines.join('\n'));
});
