// Explicit reporting evaluates the whole corpus before touching a scratch output.
import { lstatSync, realpathSync, statSync, openSync, writeFileSync, closeSync, renameSync, rmSync } from 'node:fs';
import { dirname, basename, resolve, relative, isAbsolute, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { evaluateAll } from './labeled-evaluate.mjs';

const root = realpathSync(fileURLToPath(new URL('../', import.meta.url)));
const historical = join(root, 'evidence/labeled-report.md');
function scratchTarget(output) {
  if (typeof output !== 'string' || !output.trim()) throw new Error('an explicit --output scratch path is required');
  const requested = resolve(output);
  const target = join(realpathSync(dirname(requested)), basename(requested));
  const rel = relative(root, target);
  if (!rel || (!isAbsolute(rel) && rel !== '..' && !rel.startsWith('../'))) {
    throw new Error('output must be outside the repository; accepted historical evidence is never an output target');
  }
  let existing;
  try { existing = lstatSync(target); } catch (error) { if (error.code !== 'ENOENT') throw error; }
  if (existing) {
    if (!existing.isFile()) throw new Error('output must be a regular scratch file, not a directory or symbolic link');
    const original = statSync(historical);
    if (existing.dev === original.dev && existing.ino === original.ino) throw new Error('output aliases accepted historical evidence');
  }
  return target;
}

export function generateReport(output, cases) {
  const target = scratchTarget(output);
  const rows = evaluateAll(cases);
  const body = renderReport(rows);
  const temporary = join(dirname(target), `.${basename(target)}.${randomUUID()}.tmp`);
  let fd, created = false;
  try {
    fd = openSync(temporary, 'wx', 0o600);
    created = true;
    writeFileSync(fd, body);
    closeSync(fd);
    fd = undefined;
    renameSync(temporary, target);
  } finally {
    if (fd !== undefined) closeSync(fd);
    if (created) rmSync(temporary, { force: true });
  }
  return rows;
}

const esc = s => String(s).replace(/\|/g, '\\|');
export function renderReport(results) {
  const rep = results.filter(r => r.kind === 'reported');
  const types = ['files', 'nodes', 'pe', 'vram', 'outside'];
  const per = types.map(t => { const xs = rep.filter(r => r.type === t); return [t, xs.filter(r => r.caught).length, xs.length]; });
  const caught = rep.filter(r => r.caught).length;
  const lines = [
    '# Labeled set: caught and missed', '',
    `Scratch candidate generated by \`npm run report:labeled -- --output <scratch-path>\` on ${new Date().toISOString().slice(0, 10)}. Every reported case is an edit of an official Comfy-Org template (fixtures/official).`, '',
    `**Reported problems caught: ${caught} of ${rep.length} (${Math.round(100 * caught / rep.length)}%).** Stop rule: stop below 50%.`, '',
    '| Problem type | Caught | Of |', '|---|---|---|', ...per.map(([t, a, b]) => `| ${t} | ${a} | ${b} |`), '',
    '## Controls (must raise no fail, warning or dormant finding)', '',
    '| Control | Format | Alarms | Info notes | Passes |', '|---|---|---|---|---|',
    ...results.filter(r => r.kind === 'control').map(r => `| ${r.name} | ${r.format} | ${r.alarms} | ${r.info.join(', ') || '–'} | ${r.passes} |`), '',
    '## Real ComfyUI 0.38.0 exports (templates package 0.11.70)', '',
    '| ID | Export | Format | Expected rule | Result | Reads like its template file |', '|---|---|---|---|---|---|',
    ...results.filter(r => r.kind === 'export').map(r => `| ${r.id} | ${esc(r.config)} | ${r.format} | ${r.expect} | ${r.status} | ${r.same} |`), '',
    '## Reported cases', '',
    '| ID | Type | Thread | Rebuilt configuration | Expected rule | Result | ComfyUI today |', '|---|---|---|---|---|---|---|',
    ...rep.map(r => `| ${r.id} | ${r.type} | ${r.thread} | ${r.config}${r.assumption ? ` (${r.assumption})` : ''}${r.version ? `; version ${r.version}` : ''} | ${r.expect || '–'} | ${r.caught ? `caught (${r.status})` : 'missed'} | ${r.flaggedToday} |`), '',
    '## Documented rules (source code or Qwen docs; not counted above)', '',
    '| ID | Configuration | Rule | Status |', '|---|---|---|---|',
    ...results.filter(r => r.kind === 'documented').map(r => `| ${r.id} | ${esc(r.config)} | ${r.expect} | ${r.status} |`), '',
  ];
  return lines.join('\n');
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const args = process.argv.slice(2);
    if (args.length !== 2 || args[0] !== '--output') throw new Error('usage: node tools/labeled-report.mjs --output <scratch-path>');
    const rows = generateReport(args[1]);
    console.log(`Complete scratch candidate: ${rows.length} rows written. Accepted evidence unchanged.`);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
